### ISSUE TITLE
What command should I run in wsl to start the GUI client?

### ISSUE THREAD

**Issue by imri29** [lackovic/notes#3]
**Windows Subsystem for Linux Note**
under "On WSL: run the command to start your GUI application", you mentioned the phrase in the title - can you specify the command to a newbie?

I'm unable to start the graphics environment after restart and this command may be the piece I'm missing.

Thanks, great setup!

**Comment by lackovic** [comment]
Sorry, I am not sure I understand what you mean. You don't need to start any graphic environment, you just run the command needed to start your application: e.g. if you want to start _IntelliJ IDEA_, and that is installed in the directory `/opt/intellij/` then simply type `/opt/intellij/bin/idea.sh` and press `Enter` inside WSL.

**Comment by imri29** [comment]
I see. Sorry, I was confused. Thanks for you comment!
