### ISSUE TITLE
Huge mouse cursor when launching Webstorm

### ISSUE THREAD

**Issue by delucca** [lackovic/notes#5]
Hi!

Thanks for this repo. I've followed [your WSL notes](https://github.com/lackovic/notes/tree/master/Windows/Windows%20Subsystem%20for%20Linux#run-a-linux-gui-application-in-wsl-2) but I'm facing an issue

When I launch it, Webstorm has no close/maximize buttons (it is fullscreen) and the mouse cursor is HUGE (I'm in a notebook with scaled display).

Also, for some reason, the mouse cursor is cut in the middle.

Finally, if I run `gnome-session` on WSL before launching Webstorm the issue disappears until the next reboot.

Do you know what should I do? :)

**Comment by lackovic** [comment]
> Do you know what should I do? :)

Sorry, I don't know how to help you 😕

**Comment by delucca** [comment]
> > Do you know what should I do? :)
> 
> Sorry, I don't know how to help you 😕

I've tried to do everything again, installed the X server and it seems to work as expected 🤔 

Well, closing the issue. Thanks anyway!
